### PR TITLE
Don't allow floats with the manual number source

### LINKED ISSUE #12261: Manual Number gets stuck in endless loop
**Describe the bug**
when using manual number as a source, it ends up in an endless loop when a comma value is entered.

**To Reproduce**
Steps to reproduce the behaviour:
1. create metric compliance
2. add source manual number
3. enter as value 9,25 OR 9.25

Image

**ADDITIONAL**
⚠️ please also update the documentation (https://quality-time.readthedocs.io/en/latest/reference.html#manual-number). It says nothing about the allowed values (positive natural numbers).

### PR DESCRIPTION
**Pull request by fniessink**
Fixes #12261.

### CODE REVIEW

File: components/frontend/src/widgets/buttons/ReportUploadButton.jsx [hunk 1]
```diff
@@ -34,7 +34,6 @@ export function ReportUploadButton({ reload }) {
                     data-testid="report-import-input"
                     type="file"
                     onChange={(event) => {
-                        console.log(event.target.files)
```
Comment (wkoot) [inline components/frontend/src/widgets/buttons/ReportUploadButton.jsx:37]: hehe

File: docs/src/changelog.md [hunk 2]
```diff
@@ -17,6 +17,7 @@ If your currently installed *Quality-time* version is not the penultimate versio
 ### Fixed
 
 - Clarify in the product vision that checking the correct configuration of sources is out of scope for Quality-time. Fixes [#3821](https://github.com/ICTU/quality-time/issues/3821).
+- Don't allow floats with the manual number source. Fixes [#12261](https://github.com/ICTU/quality-time/issues/12261).
```
Comment (wkoot) [inline docs/src/changelog.md:21]: I expected a backend change as well, do we not have type checking for this because the user input is all stringyfied?

File: components/frontend/src/fields/TextField.jsx [hunk 3]
```diff
@@ -39,6 +39,16 @@ export function TextField({
         }
     }
 
+    function isValid() {
+        if (required && !textValue) {
+            return false
+        }
+        if (type === "number") {
+            return /^\d+$/.test(textValue)
```
Comment (wkoot) [inline components/frontend/src/fields/TextField.jsx:47]: Hmm this feels a bit flimsy, can we not actually send an int to the backend and use the 'being able to store native types' feature?

File: docs/src/changelog.md (hunk 2 above)
Comment (fniessink) [reply docs/src/changelog.md:21]: No, we don't check the values for e.g. source parameters either in the backend.

File: components/frontend/src/fields/TextField.jsx (hunk 3 above)
Comment (fniessink) [reply components/frontend/src/fields/TextField.jsx:47]: Not sure what you mean by "the 'being able to store native types' feature"?

Comment (wkoot) [reply components/frontend/src/fields/TextField.jsx:47]: Hmm, no wait I misremembered `SourceMeasurement.entities_to_store` - this is explicitly not sent to DB but only retained within the run (and metric collectors)
