### PR TITLE
Make the "Issues" dashboard card consistent

### LINKED ISSUE #12080: Inconsistent dashboard cards
**Describe the bug**
The "Action required" and "Legend" cards have "Unknown" as first item, but the "Issues" cards has unknown as last.

The "Issues" card has no total line.
 
**Expected behaviour**
Put "Unknown" as first status in all cards as it is the most important one. 

Add a total line to the "Issues" cards.

**Screenshots**
Image

**Your environment (please complete the following information):**
 - Quality-time version v5.43.0

### PR DESCRIPTION
**Pull request by fniessink**
Make the "Issues" dashboard card consistent with other dashboard cards: put the number of unknown issues on the first line and give it a total number of issues.

Fixes #12080.

### CODE REVIEW

File: components/frontend/src/dashboard/LegendCard.jsx [hunk 1]
```diff
@@ -10,15 +10,15 @@ export function LegendCard() {
             <StatusIcon status={status} />
             <ListItemText
                 primary={STATUS_SHORT_NAME[status]}
-                slotProps={{ primary: { typography: { fontSize: "12px" } } }}
+                slotProps={{ primary: { typography: { fontSize: "1.1em" } } }}
```
Comment (wkoot) [inline components/frontend/src/dashboard/LegendCard.jsx:13]: Is it correct that this is smaller than FilterCardWithTable's `1.3em` ?

File: docs/src/changelog.md [hunk 2]
```diff
@@ -12,6 +12,12 @@ If your currently installed *Quality-time* version is not the penultimate versio
 
 <!-- The line "## <square-bracket>Unreleased</square-bracket>" is replaced by the release/release.py script with the new release version and release date. -->
 
+## [Unreleased]
+
+### Fixed
+
+- Make the "Issues" dashboard card consistent with other dashboard cards: put the number of unknown issues on the first line and give it a total number of issues. Fixes [#12080](https://github.com/ICTU/quality-time/issues/12080).
```
Comment (wkoot) [inline docs/src/changelog.md]:
```suggestion
- Make the "Issues" dashboard card consistent with other dashboard cards by putting the number of unknown issues on the first line and giving it a total number of issues. Fixes [#12080](https://github.com/ICTU/quality-time/issues/12080).
```

**Review by wkoot — APPROVED** [review]

File: components/frontend/src/dashboard/LegendCard.jsx (hunk 1 above)
Comment (fniessink) [reply components/frontend/src/dashboard/LegendCard.jsx:13]: Yes, the Legend card has more lines of text.
