### PR TITLE
Use the locale of the user's browser when exporting to PDF.

### LINKED ISSUE #8381: PDF-export ignores locale for date format
**Describe the bug**
When using the PDF-export, the headless browser ignores the host's locale settings and defaults to "en-US" for date formats.

**To Reproduce**
Steps to reproduce the behaviour:
Open report - press the "Download report as PDF" button.
Result: dates in the "About this report" section are formatted as "MM-DD-YYYY", regardless of your locale settings.

**Expected behaviour**
Date formatted according to host's locale settings, or according to the global settings for the renderer's container, which is "en-GB".

**Screenshots**
Screenshot 2024-03-29 at 11 29 00

**Your environment (please complete the following information):**
 - OS: macOS
 - Browser: Chromium headless
 - Quality-time version v5.9.0

**Possible solutions
- In the PDF-export endpoint of the API-server, pass the relevant headers of the user agent to the renderer.

### PR DESCRIPTION
**Pull request by fniessink**
Fixes #8381.

### CODE REVIEW

File: components/frontend/src/header_footer/buttons/DownloadAsPDFButton.jsx [hunk 1]
```diff
@@ -36,8 +36,11 @@ export function DownloadAsPDFButton({ report_uuid }) {
     const [loading, setLoading] = useState(false)
     // Make sure the report_url contains only registered query parameters
     const query = registeredURLSearchParams()
-    const queryString = query.toString() ? "?" + query.toString() : ""
-    query.set("report_url", window.location.origin + window.location.pathname + queryString + window.location.hash)
+    query.set("language", navigator.language)
+    query.set(
+        "report_url",
+        window.location.origin + window.location.pathname + "&" + query.toString() + window.location.hash,
```
Comment (wkoot) [inline components/frontend/src/header_footer/buttons/DownloadAsPDFButton.jsx]: Does `pathname` always contain a `?` due to setting `navigator.language`? Seems odd to still be called `pathname` then

File: components/frontend/src/header_footer/buttons/DownloadAsPDFButton.test.jsx [hunk 2]
```diff
@@ -56,7 +56,7 @@ test("DownloadAsPDFButton indicates loading on click", async () => {
     expectButtonIsLoading()
     expect(get_report_pdf.get_report_pdf).toHaveBeenCalledWith(
         "report_uuid",
-        "?report_url=http%3A%2F%2Flocalhost%3A3000%2F",
+        "?language=en-US&report_url=http%3A%2F%2Flocalhost%3A3000%2F%26language%3Den-US",
```
Comment (wkoot) [inline components/frontend/src/header_footer/buttons/DownloadAsPDFButton.test.jsx]: Should we also autotest `nl-NL` somewhere?

**Review by wkoot — APPROVED** [review]

File: components/frontend/src/header_footer/buttons/DownloadAsPDFButton.jsx (hunk 1 above)
Comment (fniessink) [reply components/frontend/src/header_footer/buttons/DownloadAsPDFButton.jsx]: Huh, there's indeed no `?`, but it does work. Apparently `&` instead of `?` works as well. But, I'll change it of course.

File: components/frontend/src/header_footer/buttons/DownloadAsPDFButton.test.jsx (hunk 2 above)
Comment (fniessink) [reply components/frontend/src/header_footer/buttons/DownloadAsPDFButton.test.jsx]: Agreed. I'll see if I can mock `navigator.language`.

File: components/frontend/src/header_footer/buttons/DownloadAsPDFButton.jsx (hunk 1 above)
Comment (wkoot) [reply components/frontend/src/header_footer/buttons/DownloadAsPDFButton.jsx]: Oh, I assumed that `query.set()` actually added a querystring to `location.pathname` somehow :D
