### PR TITLE
Don't rearrange dropdown dynamically.

### LINKED ISSUE #8745: Pop-up menu changes width unexpectedly
**Describe the bug**
the pop-up menu for adding metrics changes width when one click the checkbox for hiding metrics.

**To Reproduce**
I believe this only happens for CI-environment subject.

**Expected behaviour**

**Screenshots**
image

image

### PR DESCRIPTION
**Pull request by fniessink**
In the dropdown of the "Add metric" button, keep the two checkboxes next to each other regardless of the width of the menu.

Fixes #8745.

### CODE REVIEW

File: components/frontend/src/widgets/Button.js [hunk 1]
```diff
@@ -155,20 +195,15 @@ export function AddDropdownButton({ itemSubtypes, itemType, onClick, allItemSubt
...
-                            />
-                        )}
-                        {usedItemSubtypeKeys?.length > 0 && (
-                            <FilterCheckbox
-                                label={`Hide ${itemType} types already used`}
-                                filter={hideUsedItems}
-                                setFilter={setHideUsedItems}
-                            />
-                        )}
+                        <FilterCheckboxes
```
Comment (wkoot) [inline components/frontend/src/widgets/Button.js:198]: Nice to group the logic like this

File: components/frontend/src/widgets/Button.js [hunk 2]
```diff
@@ -155,20 +195,15 @@ export function AddDropdownButton({ itemSubtypes, itemType, onClick, allItemSubt
...
+                            itemType={itemType}
+                            allowHidingUnsupportedItems={allItemSubtypes?.length > 0}
+                            showUnsupportedItems={showUnsupportedItems}
```
Comment (wkoot) [inline components/frontend/src/widgets/Button.js:201]: Although the variable name is the same as the arg, wouldn't it be more explicit to include the word "filter" in the arg name?

Comment (wkoot) [reply components/frontend/src/widgets/Button.js:201]: Oh, nvm. I only just saw that this is also a boolean
