### PR TITLE
When copying a metric also copy entity status

### LINKED ISSUE #7403: When copying a metric, technical debt acceptance per entity is not copied.
**Describe the bug**
When copying a metric that has entities and has one or more entities with a technical debt status and/or comment, this information is not copied along. This is unexpected behaviour, because all else, like source configuration and such, will be copied when copying a metric.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to a metric that has entities and has one or more entities with a technical debt status and/or comment
2. After logging in, duplicate that metric using the copy button on the bottom of that same subject
3. Wait for the metric to gather the results
4. See that the number at the measurement field is higher in the original metric compared to the copied metric

**Expected behaviour**
When copying, everything should be copied, all config.

### PR DESCRIPTION
**Pull request by fniessink**
Fixes #7403.

### CODE REVIEW

File: components/frontend/src/source/SourceEntities.jsx [hunk 1]
```diff
@@ -235,7 +235,7 @@ export function SourceEntities({ loading, measurements, metric, metricUuid, relo
     }
     const lastMeasurement = measurements[measurements.length - 1]
     const source = lastMeasurement.sources.find((source) => source.source_uuid === sourceUuid)
-    if (!Array.isArray(source.entities) || source.entities.length === 0) {
+    if (!Array.isArray(source?.entities) || source.entities.length === 0) {
```
Comment (wkoot) [inline components/frontend/src/source/SourceEntities.jsx:238]: Additional bugfix?

File: components/shared_code/tests/shared/model/test_measurement.py [hunk 2]
```diff
@@ -282,6 +302,31 @@ def test_copy_first_seen_timestamps(self):
...
+                {
+                    "source_uuid": SOURCE_ID2,
+                    "type": "azure_devops",
+                    "entities": [{"key": "key1", "first_seen": "2023-07-17"}],
+                },
+            ],
+        )
+        measurement_2.copy_entity_first_seen_timestamps(measurement_1)
+        self.assertEqual("2023-07-15", measurement_2["sources"][0]["entities"][0]["first_seen"])
+
```
Comment (wkoot) [inline components/shared_code/tests/shared/model/test_measurement.py:329]: Missing changelog message

File: components/shared_code/tests/shared/model/test_measurement.py [hunk 3]
```diff
@@ -251,6 +251,26 @@ def test_entity_user_data(self):
...
+                },
+            ],
+        )
+        measurement_2 = Measurement(
+            self.metric(sources={SOURCE_ID2: cast(Source, {"copied_from": SOURCE_ID})}),
+            sources=[{"source_uuid": SOURCE_ID2, "type": "azure_devops"}],
+        )
+
+        measurement_2.copy_entity_user_data(measurement_1)
+        self.assertIn("entity_user_data", measurement_2.sources()[0])
```
Comment (wkoot) [inline components/shared_code/tests/shared/model/test_measurement.py]:
```suggestion
        self.assertIn("entity_user_data", measurement_2.sources()[0])
        self.assertIsNotNone(measurement_2.sources()[0]["entity_user_data"])
```

Comment (wkoot) [reply components/shared_code/tests/shared/model/test_measurement.py]: hmm maybe the walrus operator works here too, I'm not sure if that's possible :D

File: components/shared_code/tests/shared/database/test_measurements.py [hunk 4]
```diff
@@ -35,12 +35,15 @@ def test_latest_measurement(self):
 
     def test_no_latest_successful_measurement(self):
         """Test no successful measurements found."""
-        self.assertIsNone(latest_successful_measurement(self.database, self.metric))
+        self.assertIsNone(latest_measurement(self.database, self.metric, skip_measurements_with_error=True))
```
Comment (wkoot) [inline components/shared_code/tests/shared/database/test_measurements.py:38]: Shouldn't there also be a test that a measurement with error can be found? Or is it pointless to test because it's all mocked anyway

File: components/collector/tests/database/test_measurements.py [hunk 5]
```diff
@@ -106,3 +112,60 @@ def test_create_measurement_after_measurement_was_requested(self):
...
+            "copied_from": METRIC_ID,
+            "sources": {SOURCE_ID2: {"type": "pip", "copied_from": SOURCE_ID}},
+        }
+        self.database["reports"].insert_one(report)
+        create_measurement(self.database, self.measurement_data(metric_uuid=METRIC_ID2, source_uuid=SOURCE_ID2))
+        inserted_measurement = self.database.measurements.find_one(filter={"metric_uuid": METRIC_ID2})
+        self.assertNotIn("entity_user_data", inserted_measurement["sources"][0])
+
+    def test_create_measurement_for_copied_metric_without_origin(self):
+        """Test that the entity user data are not copied if the original metric was deleted."""
```
Comment (wkoot) [inline components/collector/tests/database/test_measurements.py:160]: Why does this happen, is it a strong reference? Or was the metric deleted in between clicks?

File: components/frontend/src/source/SourceEntities.jsx (hunk 1 above)
Comment (fniessink) [reply components/frontend/src/source/SourceEntities.jsx:238]: Yeah, not sure it happens in production though. I think I ran into this because a feature tests created a source without entities array.

File: components/shared_code/tests/shared/model/test_measurement.py (hunk 2 above)
Comment (fniessink) [reply components/shared_code/tests/shared/model/test_measurement.py:329]: Added.

File: components/shared_code/tests/shared/model/test_measurement.py (hunk 3 above)
Comment (fniessink) [reply components/shared_code/tests/shared/model/test_measurement.py]: I've changed the assert to: 

```python
self.assertIn("key", measurement_2.sources()[0]["entity_user_data"])
```

File: components/shared_code/tests/shared/database/test_measurements.py (hunk 4 above)
Comment (fniessink) [reply components/shared_code/tests/shared/database/test_measurements.py:38]: There is a test for that. The previous test doesn't pass `skip_measurements_with_error` so it defaults to `False` there.

File: components/collector/tests/database/test_measurements.py (hunk 5 above)
Comment (fniessink) [reply components/collector/tests/database/test_measurements.py:160]: The latter. In theory the original metric could be deleted before the copy operation is finished. I wouldn't have bothered with this test normally, but the code that copies the metric needs to get the original metric. Getting the original metric may return None, so there is indeed a code path where the original metric does not exist. Hence the unit test.
