### PR TITLE
When adding a new source to a metric, don't show the spinner until th…

### LINKED ISSUE #9994: When adding a new source, the spinner starts spinning before a connection/change is made
**Describe the bug**
When adding a new source, the spinner starts spinning before a connection/change is made

**To Reproduce**
Steps to reproduce the behaviour:
1. create metric Security Warnings
2. Add new source ZAP
3. See spinner start spinning before any change is made

**Expected behaviour**
Wait until toaster says: Connection OK

**Screenshots**
image

### PR DESCRIPTION
**Pull request by fniessink**
…e source has been configured sufficiently to start collecting data.

Fixes #9994.

### CODE REVIEW

File: components/frontend/src/utils.jsx [hunk 1]
```diff
@@ -104,12 +105,34 @@ export function isMeasurementOutdated(metric) {
...
+    // all mandatory parameters configured
+    const sources = Object.values(metric.sources ?? {})
+    if (sources.length === 0) {
+        return false
+    }
+    return sources.every((source) => {
+        const parameters = dataModel.sources[source.type].parameters
+        return Object.entries(parameters).every(([parameterKey, parameter]) => {
+            if (parameter.mandatory && parameter.metrics.includes(metric.type) && !parameter.default_value) {
+                return source?.parameters?.[parameterKey]
```
Comment (wkoot) [inline components/frontend/src/utils.jsx:125]: Why return the value here? Do we ever return `false`?

Comment (fniessink) [reply components/frontend/src/utils.jsx:125]: This is how `every` works, it takes a callback for each item that should return true or false, see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/every
