### PR TITLE
Fix documentation links.

### LINKED ISSUE #10843: read the docs links do not work
click this link

Image

the user is redirected to
https://quality-time.readthedocs.io/en/v5.23.0/reference.html#test_suites

where it should be
https://quality-time.readthedocs.io/en/v5.23.0/reference.html#test-suites

### PR DESCRIPTION
**Pull request by fniessink**
Links to documentation on Read the Docs for subjects, metrics, or sources with hyphens in their name wouldn't scroll to the right location.

Fixes #10843.

### CODE REVIEW

File: components/frontend/src/utils.jsx [hunk 1]
```diff
@@ -421,7 +421,7 @@ export function dropdownOptions(options) {
 
 export function referenceDocumentationURL(name) {
     // Return a URL to the documentation for the metric/subject/source name
-    const slug = `${name?.toLowerCase().replaceAll(" ", "-").replaceAll(/[()/]/g, "")}`
+    const slug = `${name?.toLowerCase().replaceAll(" ", "-").replaceAll("_", "-").replaceAll(/[()/]/g, "")}`
```
Comment (wkoot) [inline components/frontend/src/utils.jsx]: Is this `replaceAll` a regex? Perhaps the first can then be replaced by something like `replaceAll([\s_]), "-")`?

Comment (fniessink) [reply components/frontend/src/utils.jsx]: The first argument can be a regex yes. In JavaScript strings between slashes are regular expression literals.

Comment (fniessink) [reply components/frontend/src/utils.jsx]: Merged `replaceAll(" ", "-").replaceAll("_", "-")` into `replaceAll(/[\s_]/g, "-")`.
