### PR TITLE
Fix enabled issue tracker fields

### LINKED ISSUE #12039: Make issue tracker fields inactive when issue tracker is none
**Describe the bug**
It is possible to fill in the issue tracker fields without picking an issue tracker type. The user can think they have configured the issue tracker while Quality-time ignores the filled in values because no issue type has been picked. 

**Expected behaviour**
Make the issue tracker fields inactive until an issue tracker type has been picked.

### PR DESCRIPTION
**Pull request by fniessink**
Disable issue tracker fields until the user picks an issue tracker type.

Fixes #12039.

### CODE REVIEW

File: components/frontend/src/report/IssueTracker.jsx [hunk 1]
```diff
@@ -83,14 +83,17 @@ export function IssueTracker({ report, reload }) {
     const projectKey = report.issue_tracker?.parameters?.project_key
     const issueType = report.issue_tracker?.parameters?.issue_type
     const epicLink = report.issue_tracker?.parameters?.epic_link
+    const issueTrackerFieldDisabled = disabled || !report.issue_tracker?.type || report.issue_tracker?.type === "None"
```
Comment (wkoot) [inline components/frontend/src/report/IssueTracker.jsx:88]: Why `type: "None"` instead of `null` ?

**Review by wkoot — APPROVED** [review]

File: components/frontend/src/report/IssueTracker.jsx (hunk 1 above)
Comment (fniessink) [reply components/frontend/src/report/IssueTracker.jsx:88]: The onChange handler below would save the string "None" to the database. I've changed that, but we still have to take into account that the database may still contain "None" for the `report.issue_tracker.type` instead of a falsey value.
