### PR TITLE
Fix time ago labels.

### LINKED ISSUE #8440: Time ago label does not have a correct value any more
**Describe the bug**
Since the last release, the time ago label does not show the right value any more.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to technical debt of a metric
2. see the label at the 'Technical debt end date' field

**Screenshots**
image

### PR DESCRIPTION
**Pull request by fniessink**
The time ago or to go, shown in the labels of date fields, would be incorrect.

Fixes #8440.

### CODE REVIEW

File: components/frontend/src/metric/MetricDebtParameters.js [hunk 1]
```diff
@@ -74,7 +74,7 @@ function TechnicalDebtEndDate({ metric, metric_uuid, reload }) {
             requiredPermissions={[EDIT_REPORT_PERMISSION]}
             label={
                 <LabelWithDate
-                    date={Date(metric.debt_end_date)}
+                    date={metric.debt_end_date}
```
Comment (wkoot) [inline components/frontend/src/metric/MetricDebtParameters.js:77]: I'm surprised that there's no change in test code needed?

Comment (fniessink) [reply components/frontend/src/metric/MetricDebtParameters.js:77]: Good point. I'll add a unit test.
