### PR TITLE
Fix delete report button positioning.

### LINKED ISSUE #8338: The "Delete report" button overlaps with the report title panel
**Describe the bug**
The "Delete report" button overlaps with the report title panel:

**Screenshots**
image

**Your environment (please complete the following information):**
 - Quality-time version 5.9.0.

### PR DESCRIPTION
**Pull request by fniessink**
Fixes #8338.

### CODE REVIEW

File: components/frontend/src/report/ReportTitle.js [hunk 1]
```diff
@@ -301,7 +301,15 @@ function ButtonRow({ report_uuid, openReportsOverview }) {
         <ReadOnlyOrEditable
             requiredPermissions={[EDIT_REPORT_PERMISSION]}
             editableComponent={
-                <DeleteButton itemType="report" onClick={() => delete_report(report_uuid, openReportsOverview)} />
+                <span
+                    /* The delete button needs to be in a span with an explicit height because otherwise it is
+                       considered to have a height of zero. Maybe because it is floated right? Button rows that have
```
Comment (wkoot) [inline components/frontend/src/report/ReportTitle.js:306]: Weird! But fixed is fixed

**Review by wkoot — APPROVED** [review]
